baseURL = 'https://emils.site'
languageCode = 'en-us'
title = 'Emil Straschil'
theme = 'hextra'

[params.navbar]
  displayTitle = true
  displayLogo = true

[params.navbar.logo]
  path = "favicon.svg"
  dark = "favicon-dark.svg"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions.passthrough]
  enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [["\\[", "\\]"], ["$$", "$$"]]
inline = [["\\(", "\\)"], ["$", "$"]]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
  name = "Docs"
  pageRef = "/docs"
  weight = 2

[[menu.main]]
  name = "Search"
  weight = 4
  [menu.main.params]
    type = "search"

[[menu.main]]
  name = "Github"
  weight = 5
  url = "https://github.com/emil3tr/emil3tr.github.io"
  [menu.main.params]
    icon = "github"

[[menu.main]]
  name = "About"
  weight = 1
  pageRef = "/about"

[params.footer]
  displayPoweredBy = true